// Recompute rep/group/ownership/proximity + score/tier/needsSignal for every
// dealer, write them back to dealers.json, and regenerate the two markdown views.
// Idempotent: safe to run any time (e.g. after the owner edits signals).
const fs = require("node:fs");
const path = require("node:path");
const { assignRep, computeProximity, tagGroup } = require("../netlify/functions/lib/dealer-zones.js");
const { inferOwnership, scoreDealer, STAGES } = require("../netlify/functions/lib/dealer-scoring.js");

const ROOT = path.join(__dirname, "..");
const REG = path.join(ROOT, "netlify", "functions", "lib", "dealers.json");
const PIPE = path.join(ROOT, "docs", "dealers", "dealer-pipeline.md");
const WORK = path.join(ROOT, "docs", "dealers", "dealer-scoring-worksheet.md");
const REP_NAMES = { aaron: "Aaron", noah: "Noah", cody: "Cody" };
const TIER_ORDER = { A: 0, B: 1, C: 2 };

function enrich(d) {
  const rep = assignRep(d.state);
  const group = tagGroup(d.name);
  d.owningRep = rep;
  d.group = group;
  d.ownershipType = inferOwnership(group);
  d.ownershipInferred = true;
  if (!d.proximity) d.proximity = computeProximity(d.city, rep);
  Object.assign(d, scoreDealer(d));
  return d;
}

function sortDealers(a, b) {
  return (TIER_ORDER[a.tier] - TIER_ORDER[b.tier]) || (b.score - a.score) || a.name.localeCompare(b.name);
}

function pipelineMd(dealers) {
  const counts = { A: 0, B: 0, C: 0 };
  dealers.forEach((d) => counts[d.tier]++);
  const stageCounts = STAGES.map((s) => `${s}: ${dealers.filter((d) => d.stage === s).length}`).join(" · ");
  let md = `# Dealer Pipeline\n\n`;
  md += `_Generated by \`npm run score:dealers\` — do not edit by hand (edit the worksheet or dealers.json)._\n\n`;
  md += `**${dealers.length} dealers** · Tier A ${counts.A} · B ${counts.B} · C ${counts.C}\n\n`;
  md += `**Stages:** ${stageCounts}\n\n`;
  md += `Legend: ⚠ = provisional tier (needs truck-volume + enthusiast signal) · group name in **bold**.\n\n`;
  for (const rep of ["aaron", "noah", "cody"]) {
    const list = dealers.filter((d) => d.owningRep === rep).sort(sortDealers);
    md += `## ${REP_NAMES[rep]} (${list.length})\n\n`;
    md += `| Tier | Dealer | City | ST | Group | Stage |\n|---|---|---|---|---|---|\n`;
    for (const d of list) {
      const flag = d.needsSignal ? " ⚠" : "";
      const grp = d.group ? `**${d.group}**` : "—";
      md += `| ${d.tier}${flag} | ${d.name} | ${d.city} | ${d.state} | ${grp} | ${d.stage} |\n`;
    }
    md += `\n`;
  }
  return md;
}

function worksheetMd(dealers) {
  let md = `# Dealer Scoring Worksheet\n\n`;
  md += `Fill **Truck Volume** (high/med/low) and **Enthusiast?** (yes/no) for each dealer,\n`;
  md += `then paste values back into \`netlify/functions/lib/dealers.json\` (or hand this to Claude)\n`;
  md += `and run \`npm run score:dealers\`. Grouped by rep; tip: fill by group in one pass.\n\n`;
  for (const rep of ["aaron", "noah", "cody"]) {
    const list = dealers.filter((d) => d.owningRep === rep).sort((a, b) => a.name.localeCompare(b.name));
    md += `## ${REP_NAMES[rep]} (${list.length})\n\n`;
    md += `| Dealer | City | ST | Group | Truck Volume | Enthusiast? |\n|---|---|---|---|---|---|\n`;
    for (const d of list) {
      const grp = d.group || "—";
      const tv = d.truckVolume || "";
      const en = d.enthusiastPosture == null ? "" : (d.enthusiastPosture ? "yes" : "no");
      md += `| ${d.name} | ${d.city} | ${d.state} | ${grp} | ${tv} | ${en} |\n`;
    }
    md += `\n`;
  }
  return md;
}

function main() {
  const dealers = JSON.parse(fs.readFileSync(REG, "utf8")).map(enrich);
  fs.writeFileSync(REG, JSON.stringify(dealers, null, 2) + "\n");
  fs.writeFileSync(PIPE, pipelineMd(dealers));
  fs.writeFileSync(WORK, worksheetMd(dealers));
  const c = { A: 0, B: 0, C: 0 };
  dealers.forEach((d) => c[d.tier]++);
  console.log(`Scored ${dealers.length} dealers (A ${c.A} · B ${c.B} · C ${c.C}) → pipeline + worksheet regenerated`);
}

main();
